### PR TITLE
Draft for Peer Discovery chapter

### PR DESCRIPTION
**Pull request by henrisota**
Updated information on Peer Discovery, DHTs, Kademlia. (Bootstrap can be removed due to replicate on another chapter or further updated)

### CODE REVIEW

**Comment by shresthagrawal** [comment]
@henrisota nice work! Can you break the DHT chapter into smaller 1 or 2 chapters explaining it and 1 chapter implementing it. Also I liked the phone directory idea! Can we make the detailed description optional so a user after reading a gneric info about the DHT can directly go to the implementation where as if someone want to read more he can go to the next chapter. You can use markdown hyper link for that. 
Also looking forward for the visuals!

**Comment by acolytec3** [comment]
@henrisota Are you still interested in finishing out this PR?  We're working actively on finishing out this tutorial and your content is great, though I do agree with @shresthagrawal earlier feedback about possibly breaking it into smaller sections where there's a short overview specific to the DHT used in libp2p followed by implementation and then a longer addendum on the larger history and implementation details that you provided.

**Comment by henrisota** [comment]
@shresthagrawal @acolytec3 I believe the simplified content of the different functions Kademlia offers works as a short overview although maybe you can add something more specific.

**Comment by acolytec3** [comment]
Thanks for the update. I like the updated Dht section. Can you also remove the bootstrap section entirely as that's covered in chapter 2? 

Do you have capacity to finish out with the MDNS section?

**Comment by henrisota** [comment]
@acolytec3 I think I won't be able to finish that for the moment.

**Pull request merged**
